# Generated by Django 2.2.2 on 2019-10-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191012_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='private_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='keys',
            name='public_key',
            field=models.TextField(),
        ),
    ]
