# Generated by Django 2.2.2 on 2019-11-02 05:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_encrypted_storage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keys',
            new_name='Key',
        ),
    ]
