# Generated by Django 2.2.6 on 2019-11-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191102_0506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='encrypted_storage',
            name='file_name',
            field=models.CharField(default=0, max_length=15000),
            preserve_default=False,
        ),
    ]
