# Generated by Django 2.2.6 on 2019-11-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191106_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypted_storage',
            name='size',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
