# Generated by Django 2.2.6 on 2019-11-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_encrypted_storage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypted_storage',
            name='encrypted_blob',
            field=models.TextField(),
        ),
    ]
