# Generated by Django 2.2.2 on 2019-11-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191106_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypted_storage',
            name='encrypted_blob',
            field=models.BinaryField(),
        ),
    ]
