# Generated by Django 2.2.2 on 2019-11-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191111_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypted_storage',
            name='ext',
            field=models.CharField(default='jpg', max_length=100),
            preserve_default=False,
        ),
    ]
